### PR TITLE
chore: migrate to cli-table3

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by RobertWHurst** [comment]
Thanks for the PR 🍻 
We'll get our CI sorted and merge once ready.

**Comment by DanielRuf** [comment]
Bump. This is still relevant.

**Comment by RobertWHurst** [comment]
This package has been moved to https://github.com/RobertWHurst/Milieu. I'd create an issue, or update the readme but unfortunately I don't have permission as I don't work for FinTechDev any more.

**Comment by RobertWHurst** [comment]
You're issue has been fixed and I've published a new release.
The version is now 1.7.4.

Sorry it took so long. I don't get the notifications for FinTechDev repos anymore either.

**Pull request closed without merging**
